//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionParameters) DeepCopyInto(out *ActionParameters) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ToRevision != nil {
		in, out := &in.ToRevision, &out.ToRevision
		*out = new(int64)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcePatch)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionParameters.
func (in *ActionParameters) DeepCopy() *ActionParameters {
	if in == nil {
		return nil
	}
	out := new(ActionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionPreconditions) DeepCopyInto(out *ActionPreconditions) {
	*out = *in
	if in.ExpectedRevision != nil {
		in, out := &in.ExpectedRevision, &out.ExpectedRevision
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionPreconditions.
func (in *ActionPreconditions) DeepCopy() *ActionPreconditions {
	if in == nil {
		return nil
	}
	out := new(ActionPreconditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRule) DeepCopyInto(out *ActionRule) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRule.
func (in *ActionRule) DeepCopy() *ActionRule {
	if in == nil {
		return nil
	}
	out := new(ActionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisPolicy) DeepCopyInto(out *AegisPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisPolicy.
func (in *AegisPolicy) DeepCopy() *AegisPolicy {
	if in == nil {
		return nil
	}
	out := new(AegisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisPolicyList) DeepCopyInto(out *AegisPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AegisPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisPolicyList.
func (in *AegisPolicyList) DeepCopy() *AegisPolicyList {
	if in == nil {
		return nil
	}
	out := new(AegisPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AegisPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisPolicySpec) DeepCopyInto(out *AegisPolicySpec) {
	*out = *in
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProtectedWorkloads != nil {
		in, out := &in.ProtectedWorkloads, &out.ProtectedWorkloads
		*out = make([]ProtectedWorkload, len(*in))
		copy(*out, *in)
	}
	out.Limits = in.Limits
	out.Budgets = in.Budgets
	if in.ActionRules != nil {
		in, out := &in.ActionRules, &out.ActionRules
		*out = make([]ActionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisPolicySpec.
func (in *AegisPolicySpec) DeepCopy() *AegisPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AegisPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AegisPolicyStatus) DeepCopyInto(out *AegisPolicyStatus) {
	*out = *in
	in.CircuitBreaker.DeepCopyInto(&out.CircuitBreaker)
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AegisPolicyStatus.
func (in *AegisPolicyStatus) DeepCopy() *AegisPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AegisPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalRecord) DeepCopyInto(out *ApprovalRecord) {
	*out = *in
	in.DecidedAt.DeepCopyInto(&out.DecidedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalRecord.
func (in *ApprovalRecord) DeepCopy() *ApprovalRecord {
	if in == nil {
		return nil
	}
	out := new(ApprovalRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryAnalysis) DeepCopyInto(out *CanaryAnalysis) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryAnalysis.
func (in *CanaryAnalysis) DeepCopy() *CanaryAnalysis {
	if in == nil {
		return nil
	}
	out := new(CanaryAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryAnalysisResult) DeepCopyInto(out *CanaryAnalysisResult) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryAnalysisResult.
func (in *CanaryAnalysisResult) DeepCopy() *CanaryAnalysisResult {
	if in == nil {
		return nil
	}
	out := new(CanaryAnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryEnvVar) DeepCopyInto(out *CanaryEnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryEnvVar.
func (in *CanaryEnvVar) DeepCopy() *CanaryEnvVar {
	if in == nil {
		return nil
	}
	out := new(CanaryEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryRelease) DeepCopyInto(out *CanaryRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryRelease.
func (in *CanaryRelease) DeepCopy() *CanaryRelease {
	if in == nil {
		return nil
	}
	out := new(CanaryRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryReleaseList) DeepCopyInto(out *CanaryReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CanaryRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryReleaseList.
func (in *CanaryReleaseList) DeepCopy() *CanaryReleaseList {
	if in == nil {
		return nil
	}
	out := new(CanaryReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryReleaseSpec) DeepCopyInto(out *CanaryReleaseSpec) {
	*out = *in
	in.Release.DeepCopyInto(&out.Release)
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]CanaryStep, len(*in))
		copy(*out, *in)
	}
	out.Analysis = in.Analysis
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryReleaseSpec.
func (in *CanaryReleaseSpec) DeepCopy() *CanaryReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(CanaryReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryReleaseStatus) DeepCopyInto(out *CanaryReleaseStatus) {
	*out = *in
	if in.StepStartedAt != nil {
		in, out := &in.StepStartedAt, &out.StepStartedAt
		*out = (*in).DeepCopy()
	}
	if in.Analyses != nil {
		in, out := &in.Analyses, &out.Analyses
		*out = make([]CanaryAnalysisResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryReleaseStatus.
func (in *CanaryReleaseStatus) DeepCopy() *CanaryReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryStep) DeepCopyInto(out *CanaryStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryStep.
func (in *CanaryStep) DeepCopy() *CanaryStep {
	if in == nil {
		return nil
	}
	out := new(CanaryStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryTemplate) DeepCopyInto(out *CanaryTemplate) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]CanaryEnvVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryTemplate.
func (in *CanaryTemplate) DeepCopy() *CanaryTemplate {
	if in == nil {
		return nil
	}
	out := new(CanaryTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerSpec) DeepCopyInto(out *CircuitBreakerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerSpec.
func (in *CircuitBreakerSpec) DeepCopy() *CircuitBreakerSpec {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerStatus) DeepCopyInto(out *CircuitBreakerStatus) {
	*out = *in
	if in.OpenedAt != nil {
		in, out := &in.OpenedAt, &out.OpenedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerStatus.
func (in *CircuitBreakerStatus) DeepCopy() *CircuitBreakerStatus {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadProfile) DeepCopyInto(out *LoadProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadProfile.
func (in *LoadProfile) DeepCopy() *LoadProfile {
	if in == nil {
		return nil
	}
	out := new(LoadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyBudgets) DeepCopyInto(out *PolicyBudgets) {
	*out = *in
	out.CircuitBreaker = in.CircuitBreaker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyBudgets.
func (in *PolicyBudgets) DeepCopy() *PolicyBudgets {
	if in == nil {
		return nil
	}
	out := new(PolicyBudgets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyCheck) DeepCopyInto(out *PolicyCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyCheck.
func (in *PolicyCheck) DeepCopy() *PolicyCheck {
	if in == nil {
		return nil
	}
	out := new(PolicyCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDecision) DeepCopyInto(out *PolicyDecision) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]PolicyCheck, len(*in))
		copy(*out, *in)
	}
	in.EvaluatedAt.DeepCopyInto(&out.EvaluatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDecision.
func (in *PolicyDecision) DeepCopy() *PolicyDecision {
	if in == nil {
		return nil
	}
	out := new(PolicyDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyLimits) DeepCopyInto(out *PolicyLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyLimits.
func (in *PolicyLimits) DeepCopy() *PolicyLimits {
	if in == nil {
		return nil
	}
	out := new(PolicyLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedWorkload) DeepCopyInto(out *ProtectedWorkload) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedWorkload.
func (in *ProtectedWorkload) DeepCopy() *ProtectedWorkload {
	if in == nil {
		return nil
	}
	out := new(ProtectedWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationAction) DeepCopyInto(out *RemediationAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationAction.
func (in *RemediationAction) DeepCopy() *RemediationAction {
	if in == nil {
		return nil
	}
	out := new(RemediationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationActionList) DeepCopyInto(out *RemediationActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationActionList.
func (in *RemediationActionList) DeepCopy() *RemediationActionList {
	if in == nil {
		return nil
	}
	out := new(RemediationActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationActionSpec) DeepCopyInto(out *RemediationActionSpec) {
	*out = *in
	out.Target = in.Target
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.Preconditions != nil {
		in, out := &in.Preconditions, &out.Preconditions
		*out = new(ActionPreconditions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationActionSpec.
func (in *RemediationActionSpec) DeepCopy() *RemediationActionSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationActionStatus) DeepCopyInto(out *RemediationActionStatus) {
	*out = *in
	if in.Decision != nil {
		in, out := &in.Decision, &out.Decision
		*out = new(PolicyDecision)
		(*in).DeepCopyInto(*out)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ApprovalRecord)
		(*in).DeepCopyInto(*out)
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(Snapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationActionStatus.
func (in *RemediationActionStatus) DeepCopy() *RemediationActionStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSimulation) DeepCopyInto(out *RemediationSimulation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSimulation.
func (in *RemediationSimulation) DeepCopy() *RemediationSimulation {
	if in == nil {
		return nil
	}
	out := new(RemediationSimulation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationSimulation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSimulationList) DeepCopyInto(out *RemediationSimulationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationSimulation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSimulationList.
func (in *RemediationSimulationList) DeepCopy() *RemediationSimulationList {
	if in == nil {
		return nil
	}
	out := new(RemediationSimulationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationSimulationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSimulationSpec) DeepCopyInto(out *RemediationSimulationSpec) {
	*out = *in
	out.Target = in.Target
	in.Proposal.DeepCopyInto(&out.Proposal)
	out.Load = in.Load
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSimulationSpec.
func (in *RemediationSimulationSpec) DeepCopy() *RemediationSimulationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSimulationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSimulationStatus) DeepCopyInto(out *RemediationSimulationStatus) {
	*out = *in
	if in.Baseline != nil {
		in, out := &in.Baseline, &out.Baseline
		*out = new(SimulationMetrics)
		**out = **in
	}
	if in.Candidate != nil {
		in, out := &in.Candidate, &out.Candidate
		*out = new(SimulationMetrics)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSimulationStatus.
func (in *RemediationSimulationStatus) DeepCopy() *RemediationSimulationStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationSimulationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcePatch) DeepCopyInto(out *ResourcePatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcePatch.
func (in *ResourcePatch) DeepCopy() *ResourcePatch {
	if in == nil {
		return nil
	}
	out := new(ResourcePatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationMetrics) DeepCopyInto(out *SimulationMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationMetrics.
func (in *SimulationMetrics) DeepCopy() *SimulationMetrics {
	if in == nil {
		return nil
	}
	out := new(SimulationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimulationProposal) DeepCopyInto(out *SimulationProposal) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimulationProposal.
func (in *SimulationProposal) DeepCopy() *SimulationProposal {
	if in == nil {
		return nil
	}
	out := new(SimulationProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Snapshot) DeepCopyInto(out *Snapshot) {
	*out = *in
	in.TakenAt.DeepCopyInto(&out.TakenAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Snapshot.
func (in *Snapshot) DeepCopy() *Snapshot {
	if in == nil {
		return nil
	}
	out := new(Snapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
