"""Storefront: the customer-facing entry point (the "frontend" tier)."""

from __future__ import annotations

from typing import Any

from fastapi import FastAPI, Header
from fastapi.responses import HTMLResponse

from shopflow.app import Runtime, build_app

PAGE = """<!doctype html><html><head><title>ShopFlow</title></head>
<body style="font-family:system-ui;margin:2rem"><h1>ShopFlow</h1>
<p>Demo storefront operated by AegisOps. Traffic is generated by the load generator.</p></body></html>"""


def register(app: FastAPI, rt: Runtime) -> None:
    @app.get("/", response_class=HTMLResponse)
    async def home() -> str:
        return PAGE

    @app.get("/products")
    async def products() -> dict[str, Any]:
        return await rt.upstreams.json("api-gateway", "GET", "/api/products")

    @app.post("/login")
    async def login(body: dict[str, Any]) -> dict[str, Any]:
        return await rt.upstreams.json("api-gateway", "POST", "/api/auth/login", json=body)

    @app.post("/checkout")
    async def checkout(body: dict[str, Any], authorization: str = Header(default="")) -> dict[str, Any]:
        return await rt.upstreams.json("api-gateway", "POST", "/api/orders", json=body,
                                       headers={"Authorization": authorization})


def create_app() -> FastAPI:
    return build_app("storefront", register)
