apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - sandbox.yaml
  - postgres.yaml
  - controller.yaml
  - app.yaml
  - frontend.yaml
  - policy.yaml
  - network-policy.yaml
