apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aegisops.io_aegispolicies.yaml
  - aegisops.io_canaryreleases.yaml
  - aegisops.io_remediationactions.yaml
  - aegisops.io_remediationsimulations.yaml
